#!/usr/bin/env python3
"""Embed a small .mtpt container into a classic-script JS file.

The visualizer is a static page that also works from file://, where fetch() of
sibling files is blocked, so the small teaching workload ships inside the page
as base64. Usage:

    python3 viz/embed_small.py viz/traces/matmul_8.mtpt viz/traces/matmul_8.js
"""
import base64
import sys


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: embed_small.py IN.mtpt OUT.js", file=sys.stderr)
        return 2
    data = open(sys.argv[1], "rb").read()
    if data[:4] != b"MTPT":
        print("not an MTPT container", file=sys.stderr)
        return 1
    if len(data) > 4 * 1024 * 1024:
        print("refusing to embed a container over 4 MiB; open it with the file picker instead",
              file=sys.stderr)
        return 1
    b64 = base64.b64encode(data).decode("ascii")
    with open(sys.argv[2], "w") as out:
        out.write("// Generated by viz/embed_small.py from %s (%d bytes). Do not edit.\n"
                  % (sys.argv[1], len(data)))
        out.write("window.MTPT_EMBEDDED = window.MTPT_EMBEDDED || [];\n")
        out.write("window.MTPT_EMBEDDED.push({name: %r, base64: %r});\n"
                  % (sys.argv[1].split("/")[-1], b64))
    print("embedded %s (%d bytes) into %s" % (sys.argv[1], len(data), sys.argv[2]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
